version: 2.1
jobs:
  test:
    docker:
      - image: dkhamsing/awesome_bot
    steps:
      - checkout
      - run:
          name: Test links
          command: |
            cd docs/
            awesome_bot --allow-dupe --allow-redirect --allow 403 --skip-save-results `find . -name "*.md"`

workflows:
  version: 2.1
  workflow_test:
      jobs:
        - test
