version: 2.1
jobs:
  links-check:
    docker:
      - image: dkhamsing/awesome_bot
    parallelism: 50
    steps:
      - checkout
      - run:
          name: Test links
          command: |
            cd docs/
            find . -name '*.md' | circleci tests split > /tmp/test-docs
            awesome_bot \
            --allow-dupe \
            --allow-redirect \
            --white-list angel.co,etherscan.io,kovan.etherscan.io,polygon-mumbai.infura.io,polygon-mainnet.infura.io,project/measures/metric,api.llama.fi/protocol/project-slug,data-api.defipulse.com/api/v1/defipulse/api/GetHistory?project=project-slug,github.com/Project/KPI/blob/master/README.md,github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/project-slug/index.js,mario.cash,zelda.cash \
            --skip-save-results \
            $(cat /tmp/test-docs)
  spelling-check:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Test doc spelling
          command: |
            sudo npm i markdown-spellcheck -g
            ./ci/spelling-check.sh

workflows:
  version: 2.1
  workflow_test:
      jobs:
        - links-check
        - spelling-check

  workflow_nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
          - links-check
          - spelling-check
