version: 2.1
jobs:
  test:
    docker:
      - image: dkhamsing/awesome_bot
    parallelism: 80
    steps:
      - checkout
      - run:
          name: Test links
          command: |
            pwd
            circleci tests glob "docs/**/*.md" | circleci tests split > /tmp/test-docs
            awesome_bot --allow-dupe --allow-redirect --allow 403 --skip-save-results $(echo '$(cat /tmp/test-docs)')


workflows:
  version: 2.1
  workflow_test:
      jobs:
        - test
