version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.0.1
    steps:
      - checkout
      - run:
          name: Test links
          command: |
            gem install awesome_bot
            cd docs/
            find . -type d -exec bash -c 'cd "$0" && awesome_bot --allow-redirect --allow-dupe --allow-ssl *' {} \;

workflows:
  version: 2.1
  workflow_test:
      jobs:
        - test
