version: 2.1
jobs:
  test:
    docker:
      - image: dkhamsing/awesome_bot
    parallelism: 80
    steps:
      - checkout
      - run:
          name: Test links
          command: |
            cd docs/
            pwd
            circleci tests glob "*.md" | circleci tests split > /tmp/test-docs
            cat /tmp/test-docs
            #awesome_bot --allow-dupe --allow-redirect --allow 403 --skip-save-results $(cat /tmp/test-docs)


workflows:
  version: 2.1
  workflow_test:
      jobs:
        - test
